// packages/react-native/src/useChat.ts
import { useEffect, useRef, useSyncExternalStore } from 'react'
import { createChatController } from '@agentskit/core'
import type { ChatConfig, ChatController, ChatReturn } from '@agentskit/core'

/**
 * React Native / Expo `useChat`. Identical contract to
 * `@agentskit/react` — imported from a pure-React module so it stays
 * Metro / Hermes safe (no DOM).
 */
export function useChat(config: ChatConfig): ChatReturn {
  const controllerRef = useRef<ChatController | null>(null)
  if (!controllerRef.current) {
    controllerRef.current = createChatController(config)
  }

  useEffect(() => {
    controllerRef.current?.updateConfig(config)
  }, [config])

  const state = useSyncExternalStore(
    controllerRef.current.subscribe,
    controllerRef.current.getState,
    controllerRef.current.getState,
  )

  return {
    ...state,
    send: controllerRef.current.send,
    stop: controllerRef.current.stop,
    retry: controllerRef.current.retry,
    edit: controllerRef.current.edit,
    regenerate: controllerRef.current.regenerate,
    setInput: controllerRef.current.setInput,
    clear: controllerRef.current.clear,
    approve: controllerRef.current.approve,
    deny: controllerRef.current.deny,
  }
}

// packages/solid/src/useChat.ts
import { createStore } from 'solid-js/store'
import { onCleanup } from 'solid-js'
import { createChatController } from '@agentskit/core'
import type { ChatConfig, ChatReturn, ChatState } from '@agentskit/core'

/**
 * Solid hook — returns a reactive chat state + controller actions.
 */
export function useChat(config: ChatConfig): ChatReturn {
  const controller = createChatController(config)
  const [state, setState] = createStore<ChatState>(controller.getState())
  const unsubscribe = controller.subscribe(() => setState(controller.getState()))
  onCleanup(() => unsubscribe())

  return new Proxy(
    {
      send: controller.send,
      stop: controller.stop,
      retry: controller.retry,
      edit: controller.edit,
      regenerate: controller.regenerate,
      setInput: controller.setInput,
      clear: controller.clear,
      approve: controller.approve,
      deny: controller.deny,
    },
    {
      get(target, prop: string) {
        if (prop in target) return (target as Record<string, unknown>)[prop]
        return (state as unknown as Record<string, unknown>)[prop]
      },
    },
  ) as unknown as ChatReturn
}
